"""Add is_trial to ParsedReceipts

Revision ID: 54e11b55fb8e
Revises: 5e74713e21a2
Create Date: 2026-03-18 11:06:32.510592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54e11b55fb8e'
down_revision: Union[str, None] = '5e74713e21a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsedreceipts', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.alter_column('parsedreceipts', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('parsedreceipts', 'receipt_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsedreceipts', 'receipt_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('parsedreceipts', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_column('parsedreceipts', 'is_trial')
    # ### end Alembic commands ###
