"""Initial subscription architecture models

Revision ID: 5e74713e21a2
Revises: 
Create Date: 2026-03-18 09:35:10.350437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e74713e21a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsedreceipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsedreceipts_merchant_name'), 'parsedreceipts', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_parsedreceipts_message_id'), 'parsedreceipts', ['message_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('raw_merchant_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('periodicity', sa.String(), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_raw_merchant_name'), 'subscriptions', ['raw_merchant_name'], unique=False)
    op.create_table('yandexconnections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_uid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yandexconnections_email'), 'yandexconnections', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yandexconnections_email'), table_name='yandexconnections')
    op.drop_table('yandexconnections')
    op.drop_index(op.f('ix_subscriptions_raw_merchant_name'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_parsedreceipts_message_id'), table_name='parsedreceipts')
    op.drop_index(op.f('ix_parsedreceipts_merchant_name'), table_name='parsedreceipts')
    op.drop_table('parsedreceipts')
    op.drop_table('users')
    # ### end Alembic commands ###
